config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :orders, only: %i[index update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/discount.rb
# frozen_string_literal: true

class Discount < Offer
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
end

app/models/oder_offer.rb
# frozen_string_literal: true

class OderOffer < ApplicationRecord
  belongs_to :order
  belongs_to :promotion, foreign_key: :offer_id, optional: true
  belongs_to :discount, foreign_key: :offer_id, optional: true
end

app/models/offer.rb
# frozen_string_literal: true

class Offer < ApplicationRecord
  has_many :orders, through: :order_offers
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :order_items
  has_many :order_offer
  has_many :promotions, through: :order_offer
  has_many :discounts, through: :order_offer

  before_create :set_uuid

  scope :open, -> { where(state: 'OPEN') }

  def amount
    ::Orders::AmountCalculator.new(self).total_amount
  end

  private

  def set_uuid
    self.uuid ||= SecureRandom.uuid
  end
end

app/models/order_item.rb
# frozen_string_literal: true

class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :pizza
  belongs_to :pizza_size

  attr_accessor :promotion_item

  def amount
    add_on_sum = add_on_price
    return pizza_price unless add_on_sum.positive?

    pizza_price + add_on_price
  end

  def pizza_price
    pizza.price * pizza_size.multiplier
  end

  def add_on_price
    ingredents = Ingredient.where(name: add)
    ingredents.map { |ingredent| ingredent.multiplier * pizza_size.multiplier }.sum
  end
end

app/models/order_offer.rb
# frozen_string_literal: true

class OrderOffer < ApplicationRecord
  belongs_to :order
  belongs_to :offer
  belongs_to :promotion, foreign_key: :offer_id, optional: true
  belongs_to :discount, foreign_key: :offer_id, optional: true
end

app/models/pizza.rb
# frozen_string_literal: true

class Pizza < ApplicationRecord
  has_many :order_items
end

app/models/pizza_size.rb
# frozen_string_literal: true

class PizzaSize < ApplicationRecord
end

app/models/promotion.rb
# frozen_string_literal: true

class Promotion < Offer
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :set_order, only: %i[update]

  def index
    @orders = Order.open
  end

  def update
    respond_to do |format|
      if @order.update(state: 'COMPLETED')
        format.turbo_stream { render turbo_stream: turbo_stream.remove(@order) }
        format.html { redirect_to orders_path, notice: 'Order marked as completed.' }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_order
    @order = Order.find(params.expect(:id))
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
  def offer_codes offers
    offers.pluck(:code).join(', ').presence
  end 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Evermood Challenge" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_order.html.erb
<%= turbo_frame_tag dom_id(order) do %>
  <div id="<%= dom_id(order) %>">
    <div class="order-left">
      <p>Order ID: <%= order.uuid %></p>
      <p>Created At: <%= order.created_at %></p>
      <p>Promotions: <%= "#{ offer_codes(order.promotions) || '-'}" %></p>
      <p>Discounts: <%= "#{ offer_codes(order.discounts) || '-'}" %></p>
      <p>Total price: <%= order.amount %></p>
    </div>
    <div class="order-right">
      <ul>
        <% order.order_items.each do |item| %>
          <li><%= item.pizza.name %> (<%= item.pizza_size.name %>)</li>
          <% if item.add.present? %>
            <ul>
              <li>Add: <%= item.add.join(', ')%></li>
            </ul>
          <% end %>
          <% if item.remove.present?%>
            <ul>
              <li>Remove: <%= item.remove.join(', ')%></li>
            </ul>
          <% end %>
        <% end %>
      </ul>
    </div>
    
    <%= button_to "Mark as Completed", order_path(order), method: :patch, data: { turbo_frame: dom_id(order), turbo_confirm: "Are you sure?" } %>
    <hr>
  </div>
<% end %>

app/views/orders/destroy.turbo_stream.erb
<%= turbo_stream.remove @order %>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Orders" %>

<h1>Orders</h1>
<hr>
<div id="orders">
  <% @orders.each do |order| %>
    <%= turbo_stream_from 'orders' %>
    <%= render order %>
  <% end %>
</div>